### PR TITLE
Getting-started.md and docker-compose.yml

### PR DESCRIPTION
**Pull request by GideonFlynn**
I made a docker-compose file which gets all services up and running after one has followed the steps I've specified in the guide.

I've also changed web's dependencies from SQLite to PostgreSQL (pg and pg-hstore).

To achieve this Docker easiness, I had to stop RSK from synchronizing its models when running. I have the understanding that Passport shouldn't be included in web and have therefore begun a removal, although I'm not removing dependencies or code, to keep clarity until it's actually removed.

### CODE REVIEW

**Comment by frenzzy** [comment]
Awesome!
I would like to merge this PR, but could you please undo all changes for `web/*`?
```shell
git remote add app-starter-kit https://github.com/kriasoft/app-starter-kit.git
git checkout app-starter-kit/master -- web/*
git commit --message "Undo changes for 'web/*'"
git push origin master
```
For changing content of `web/` or `api/` folders need to send separate PRs to [RSK](https://github.com/kriasoft/react-starter-kit) and [NSK](https://github.com/kriasoft/nodejs-api-starter) repositories respectively. By the way NSK already contain `pg` dependency, and we are going to remove data layer dependencies from RSK.
Thank you!

**Comment by GideonFlynn** [comment]
I will make the changes when I get to a computer! Would you mind that I made a separate PR with your suggested changes(undoing changes to /web) from another account? It would be a new account, but with my new, official credentials I'd like to use in the future.

Also,  should I open issues before making a PR? It seems like a good way to keep everybody on the pulse and making sure everything goes as planned.

**Comment by frenzzy** [comment]
You can use any account which have permissions to modify the PR.
About issues it's up to you really, what do you think is better..

**Comment by GideonFlynn** [comment]
Okay, I'll use this account for now, however I am not able to undo the changes the way you've specified. Should I just make the changes manually and squash the commits?

I did follow your steps and everything seemed fine but for some reason nothing changes in this PR or my commits.

Please note that I'm not that experienced with git and this is my first PR so I'm probably missing some basic step or configuration. Sorry about that. :)

**Comment by frenzzy** [comment]
merged in 195e3e1afb9a1ca922a117a246cc67c5c3091832

**Pull request closed without merging**
